<?php

namespace app\components;
use yii\base\Widget;
use app\models\CategoryV;
use yii;

class MenuWidgetV extends Widget{

    public $tpl;
    public $data;
    public $tree;
    public $menuHtml;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->tpl === null){
            $this->tpl = 'menu_v';
        }
        $this->tpl .= '.php';
    }

    public function run(){
        //get cache
        $menu_v = Yii::$app->cache->get('menu_v');
        if($menu_v) return $menu_v;
        $this->data = CategoryV::find()->indexBy('id')->asArray()->all();
        $this->tree = $this->getTree();
        $this->menuHtml = $this->getMenuHtml($this->tree);
        //set cache
        Yii::$app->cache->set('menu_v', $this->menuHtml, 60);
//	        debug($this->tree);
//	        debug($this->data);
        return $this->menuHtml;
//          return $this->tpl;
    }
    protected function getTree(){
        $tree = [];
        foreach ($this->data as $id=>&$node){
            if (!$node['parent_id'])
                $tree[$id] = &$node;
            else
                $this->data[$node['parent_id']]['child'][$node['id']] = &$node;
        }
        return $tree;
    }

    protected function getMenuHtml($tree){
        $str = '';
        foreach ($tree as $categoryv){
            $str .= $this->catToTemplate($categoryv);
        }
        return $str;
    }
    protected function catToTemplate($categoryv){
        ob_start();
        include __DIR__ . '/menu_tpl/' . $this->tpl;
        return ob_get_clean();
    }

}


