name: Copy files to remote server via scp
on: [push]
jobs:

  build:
    name: Push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        passphrase: ${{ secrets.PASSPHRASE }}
        key: ${{ secrets.PRIVATEKEY }}
        port: ${{ secrets.PORT }}
        source: "*"
        target: "ndki/ndki.loc/"
