<?php


namespace app\models;
use yii\db\ActiveRecord;


class Article extends ActiveRecord
{
    public static function tableName()
    {
        return 'articles'; // TODO: Change the autogenerated stub
    }
    public function getCategory(){
        return $this->hasOne(Category::className(),['id'=>'cat_id']);
    }
}